//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaraEducationHubClient.eTeacherServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeviewDataType", Namespace="http://schemas.datacontract.org/2004/07/KaraEducationManagermentService")]
    [System.SerializableAttribute()]
    public partial class TreeviewDataType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayData {
            get {
                return this.DisplayDataField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayDataField, value) != true)) {
                    this.DisplayDataField = value;
                    this.RaisePropertyChanged("DisplayData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eTeacherServiceReference.IeTeacherService")]
    public interface IeTeacherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeTeacherService/DoWork", ReplyAction="http://tempuri.org/IeTeacherService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeTeacherService/DoWork", ReplyAction="http://tempuri.org/IeTeacherService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeTeacherService/RegisterTeacher", ReplyAction="http://tempuri.org/IeTeacherService/RegisterTeacherResponse")]
        bool RegisterTeacher(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeTeacherService/RegisterTeacher", ReplyAction="http://tempuri.org/IeTeacherService/RegisterTeacherResponse")]
        System.Threading.Tasks.Task<bool> RegisterTeacherAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeTeacherService/GetListClass", ReplyAction="http://tempuri.org/IeTeacherService/GetListClassResponse")]
        KaraEducationHubClient.eTeacherServiceReference.TreeviewDataType GetListClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IeTeacherService/GetListClass", ReplyAction="http://tempuri.org/IeTeacherService/GetListClassResponse")]
        System.Threading.Tasks.Task<KaraEducationHubClient.eTeacherServiceReference.TreeviewDataType> GetListClassAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IeTeacherServiceChannel : KaraEducationHubClient.eTeacherServiceReference.IeTeacherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IeTeacherServiceClient : System.ServiceModel.ClientBase<KaraEducationHubClient.eTeacherServiceReference.IeTeacherService>, KaraEducationHubClient.eTeacherServiceReference.IeTeacherService {
        
        public IeTeacherServiceClient() {
        }
        
        public IeTeacherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IeTeacherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IeTeacherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IeTeacherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool RegisterTeacher(string username, string password) {
            return base.Channel.RegisterTeacher(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterTeacherAsync(string username, string password) {
            return base.Channel.RegisterTeacherAsync(username, password);
        }
        
        public KaraEducationHubClient.eTeacherServiceReference.TreeviewDataType GetListClass() {
            return base.Channel.GetListClass();
        }
        
        public System.Threading.Tasks.Task<KaraEducationHubClient.eTeacherServiceReference.TreeviewDataType> GetListClassAsync() {
            return base.Channel.GetListClassAsync();
        }
    }
}
